name: Deploy to AWS

on:
  workflow_dispatch

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print OIDC token (for debugging only!)
        run: |
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN > token.jwt
          cat token.jwt
        shell: bash


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::761200394165:role/GithubActionsOIDCRole
          aws-region: us-east-1

      - name: Run AWS CLI command
        run: aws s3 ls
