name: Deploy to AWS

on:
  workflow_dispatch

permissions:
  id-token: write    # Required for OIDC
  contents: read     # Required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload OIDC token for debugging (optional)
        run: echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" > token.jwt

      - name: Upload token as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: oidc-token
          path: token.jwt

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::761200394165:role/githubactions
          aws-region: us-east-1
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # or whichever version you need

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan
